### ISSUE TITLE
Keyboard offset

### ISSUE THREAD

**Issue by romanyczn1** [exyte/PopupView#191]
Hello, why in opaque mode and vertical position we do not change view position when keyboard appears
<img width="685" alt="keyb" src="https://github.com/exyte/PopupView/assets/57499148/82a1ec5b-4e94-4e3e-96c2-a0b5f8bee66f">

**Comment by f3dm76** [comment]
Hey @romanyczn1, because for bottom popup it's pretty obvious how to react to keyboard, but for middle one it's not. You could mean for it to stay in place, move up so it is now in the middle of the available place, stay exactly on top of keyboard, etc. If I just move it up for the height of the keyboard - it will most likely not be the desired behaviour. Also everything changes depending on if it fits the space left at all. Should I auto add a ScrollView? It's too much to assume from my side, so it's up to the user to control keyboard avoidance in this case.
