### ISSUE TITLE
Feature Request: Queue

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [exyte/PopupView#20]
First off I'm happy with the library, it made showing a popup easy. I'd very much like to queue them and have found that to be somewhat cumbersome on my end. Any chance you could add either some kind of dismiss callback, make the binding value passed in set to false when autohide happens, or just build some nice API for queuing popups?

**Comment by f3dm76** [comment]
Hey @Tyler-Keith-Thompson, thanks for your kind words! I've added dismiss callback (version 0.0.12, you are most welcome to check it out). Binding value should be changed as it is - otherwise it wouldn't have worked, I guess, but please do let me know if that is not the case. As for nice API, I think chaining them using dismiss callback is as nice as it gets - otherwise it's just going to get in-evident and heavy, but I'm open to ideas if you had anything in mind. Have a great day!

**Comment by f3dm76** [comment]
Hey @Tyler-Keith-Thompson, did the dismiss callback help? May I close the issue, or would you like some more functionality?

**Comment by Tyler-Keith-Thompson** [comment]
Oh sorry! I thought I had responded to this a while ago and apparently never did. Your callback did the trick and I ended up building my own thing around it to queue up messages.

Thank you for your quick addition
