### ISSUE TITLE
Previous floater popup is showing on a sheet view if you pull down and releases 

### ISSUE THREAD

**Issue by kiddlima** [exyte/PopupView#21]

**Comment by mkfiddle** [comment]
Also experiencing this behaviour, will try to provide more detailed report.

**Comment by f3dm76** [comment]
Hey @kiddlima, sorry for the late answer. I'm not sure I understand exactly what's going on. Are you displaying a floater on a system sheet? Can't you just manually set flag for floater when you need it to hide? Anyway, if you still having trouble with this one, could you please provide you example code, and specify exactly what sort of behaviour you need instead of what you see. Have a great day!

**Comment by f3dm76** [comment]
Hey @kiddlima, I'm going to close the issue since it's been a while. Please do reach out if you are still having problems with this. Have a nice day!
