### ISSUE TITLE
Add .popup(item:) variant

### ISSUE THREAD

**Issue by JetForMe** [exyte/PopupView#51]
There's a need to pass information to the toast UI. SwiftUI handles this for various views by providing an `item` variant for view modifiers:

```swift
    public func popover<Item, Content>(item: Binding<Item?>, attachmentAnchor: PopoverAttachmentAnchor = .rect(.bounds), arrowEdge: Edge = .top, @ViewBuilder content: @escaping (Item) -> Content) -> some View where Item : Identifiable, Content : View
```

I'm looking at your code and wondering how hard it would be to add the same thing, but I don't quite understand everything you're doing in yours.

**Comment by f3dm76** [comment]
Hey @JetForMe, it's been a while, sorry for that, but I am happy to announce that I added the item variant in version 1.0.7! Unfortunately it forces the item to be Equitable and not just Identifiable like .sheet does, since I have to subscribe to it with .onChange. Please give it a go, and do let me know if anything doesn't work as expected. Have a marvellous day!

**Comment by JetForMe** [comment]
Thanks! I'm no longer on that project so I'm not sure when I'll get to it next. But I appreciate the work!

**Comment by thebarndog** [comment]
@f3dm76 it looks like this issue should be reopened because while the popup modifier does now take an item, it doesn't pass that item into the `view` closure. When non-nil, the item should be passed into the view building closure, making the signature look like `@ViewBuilder view: @escaping (Item) -> PopupContent`.

**Comment by f3dm76** [comment]
Ok, guys I'll give it a look once I have a minute, have a good day!

**Comment by thebarndog** [comment]
I took a stab at it but I couldn't quite figure it out. I think in order to do it correctly you'll need two underlying modifiers, one that takes a view with no item and one that does. From there, the biggest issue I ran into was the dismissal animation when the view is set to autohide. Doing something like this

```swift
let sheet = ZStack {
    if let item = item {
        self.view(item)
            .addTapIfNotTV(if: closeOnTap) {
                dismiss()
            }
            .frameGetter($sheetContentRect, $sheetSafeArea)
            .offset(x: 0, y: currentOffset)
            .animation(animation)
    } else {
        EmptyView()
    }
}
```

doesn't work because the view will disappear as soon as `item == nil`. You somehow have to memoize the view closure when the `item` isn't nil and keep it around so the animation can kick in. I couldn't figure it out unfortunately.

**Comment by f3dm76** [comment]
Hey @thebarndog, you could probably have a weak copy of item which holds the latest non-nil version of item and return this copy in self.view(item). If that doesn't work for you I think we should just stick to using it like this:
```
.popup(item: $showingPopupItem, type: .`default`, closeOnTap: false) {
            if showingPopupItem = showingPopupItem {
                       // bla bla
            }
}
```
Have a wonderful day!

**Comment by thebarndog** [comment]
Tried that, doesn't seem to work either. And I could use that method but I'd prefer to use the `item` variant.

**Comment by f3dm76** [comment]
Hey @thebarndog, I'm happy to let you know I added the Item param into return closure as you asked, please check out version 1.1.4. Have a marvellous day!

**Comment by thebarndog** [comment]
That's excellent, thank you so much for doing that! I figured out the context I was missing when I tried to implement it which is SwiftUI transitions and placing the content in a `ZStack` so that insertions and removals get animated but it seems like you're on top of it :)

**Comment by f3dm76** [comment]
Hey @thebarndog, sorry to let you know I had to revert these changes, because the hiding animation didn't work. It looks like the only way to keep showing the popup during the hiding animation is to make a copy of the `item`, which is a bad idea. Please let me know if you have any ideas of a possible solution, or by any means pleased do make a PR. Have a nice day!

**Comment by thebarndog** [comment]
@f3dm76 you don't have to make a copy, as my comment above says, you have to embed everything in a ZStack and apply a transition so that when `item` is inserted or removed, that gets animated.
